name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    # steps:
    #   - uses: actions/checkout@v2
    #   - uses: actions/setup-node@v2
    #     with:
    #       node-version: '14.15.0'
    #
    #   - name: npm install
    #     run: npm install
    #
    #   - name: eslint
    #     run: |
    #       npx eslint "pages/*.vue"
    #       npx eslint "components/*.vue"
    #       npx eslint "store/*.js"
    #
    #   - name: npm run generate
    #     run: npm run generate
    #
    #   - name: npm run deploy
    #     run: npm run deploy -- --token=${{ secrets.FIREBASE_TOKEN }}
